function remappedLabel = groundTruthModulation(originalLabel)
    % Define the label mapping as a structure
    labelMap = struct(...
        'psk2', 'bpsk', ...
        'psk4', 'qam/psk', ...
        'psk8', 'qam/psk', ...
        'psk16', 'qam/psk',...
        'msk','msk/gmsk', ...
        'fsk2', 'fsk/gfsk', ...
        'fsk4','fsk/gfsk', ...
        'fsk8', 'fsk/gfsk', ...
        'fsk16', 'fsk/gfsk',...
        'gfsk', 'fsk/gfsk', ...
        'qam4','qam/psk',...
        'qam8','qam/psk',...
        'qam16', 'qam/psk',...
        'qam32', 'qam/psk',...
        'qam64','qam/psk');

    % Check if the original label is in the map
    if isfield(labelMap, originalLabel)
        % Get the remapped label from the map
        remappedLabel = labelMap.(originalLabel);
    else
        % If the original label is not in the map, use a default value
        remappedLabel = 'UnknownLabel';
    end
end
