function remappedLabel = groundTruthModulation(originalLabel)
    % Define the label mapping as a structure
    labelMap = struct(...
        'psk2', 'bpsk', ...
        'ook', 'ook',...
        'psk', 'qam/psk',...
        'psk4', 'qam/psk', ...
        'qpsk', 'qam/psk',...
        'psk8', 'qam/psk', ...
        'psk16', 'qam/psk',...
        'psk32', 'qam/psk',...
        'psk64', 'qam/psk',...
        'msk','msk/gmsk', ...
        'gmsk','msk/gmsk',...
        'fsk2', 'g/fsk2', ...
        'fsk4','fsk4', ...
        'fsk8', 'fsk8', ...
        'fsk16', 'g/fsk16',...
        'gfsk', 'g/fsk2', ...
        'qam4','qam/psk',...
        'qam8','qam/psk',...
        'qam16', 'qam/psk',...
        'qam32', 'qam/psk',...
        'qam64','qam/psk', ...
        'qam256','qam/psk',...
        'dssspsk2','dsss',...
        'dssspsk4','dsss', ...
        'dssspsk8','dsss', ...
        'dssspsk16','dsss', ...
        'dssspsk32','dsss',...
        'dssspsk64','dsss',...
        'dsssqam4', 'dsss', ...
        'dsssqam8', 'dsss', ...
        'dsssqam16', 'dsss', ...
        'dsssqam64','dsss',...
        'dsssqam256','dsss',...
        'vanilla','unknown', ...
        'ble','ble', ...
        'data','wifi_ax', ...
        'ofdm','ofdm', ...
        'zigbee','zigbee', ...
        'gsm','gsm', ...
        'wifidsss','wifidsss');

    % Check if the original label is in the map
    if isfield(labelMap, originalLabel)
        % Get the remapped label from the map
        remappedLabel = labelMap.(originalLabel);
    else
        % If the original label is not in the map, use a default value
        remappedLabel = 'UnknownLabel';
    end
end
